name: restaurant_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  data:
    path: data
  domain:
    path: domain

  cupertino_icons: ^1.0.8
  auto_route: ^10.0.1
  get_it: ^8.0.3
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  logger: ^2.5.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  freezed_annotation: ^3.0.0
  bloc_concurrency: ^0.3.0
  extended_image: ^10.0.1
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  freezed: ^3.0.6
  bloc_test: ^10.0.0
  mockito: ^5.4.6

flutter:

  uses-material-design: true
  
  assets:
    - .env
    - assets/images/temp/

flutter_intl:
  enabled: true
